# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ALAN.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ALAN(object):
    def setupUi(self, ALAN):
        ALAN.setObjectName("ALAN")
        ALAN.resize(650, 800)
        self.centralwidget = QtWidgets.QWidget(ALAN)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 650, 150))
        self.frame.setStyleSheet("background-color:rgb(40,40,39);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.bot_image = QtWidgets.QLabel(self.frame)
        self.bot_image.setGeometry(QtCore.QRect(230, 0, 191, 141))
        self.bot_image.setStyleSheet("border-radius:none;")
        self.bot_image.setText("")
        self.bot_image.setPixmap(QtGui.QPixmap("icon2.jpeg"))
        self.bot_image.setScaledContents(True)
        self.bot_image.setObjectName("bot_image")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 650, 650, 150))
        self.frame_2.setStyleSheet("background-color:rgb(40, 40, 39);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Start_Button = QtWidgets.QPushButton(self.frame_2)
        self.Start_Button.setGeometry(QtCore.QRect(540, 30, 91, 91))
        self.Start_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("mic2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Start_Button.setIcon(icon)
        self.Start_Button.setIconSize(QtCore.QSize(100, 100))
        self.Start_Button.setObjectName("Start_Button")
        self.Exit_Button = QtWidgets.QPushButton(self.frame_2)
        self.Exit_Button.setGeometry(QtCore.QRect(370, 40, 121, 81))
        self.Exit_Button.setStyleSheet("color:rgb(102, 220, 220);\n"
"background-color:rgb(40, 40, 39);\n"
"border-radius:none;\n"
"font-size:28px;")
        self.Exit_Button.setObjectName("Exit_Button")
        self.textBrowser_Date = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_Date.setGeometry(QtCore.QRect(20, 20, 256, 41))
        self.textBrowser_Date.setStyleSheet("background-color:rgb(40,40,39);\n"
"font-size:24px;\n"
"color:rgb(102, 220, 220);\n"
"border-radius:none;")
        self.textBrowser_Date.setObjectName("textBrowser_Date")
        self.textBrowser_Time = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_Time.setGeometry(QtCore.QRect(20, 90, 256, 41))
        self.textBrowser_Time.setStyleSheet("background-color:rgb(40,40,39);\n"
"font-size:24px;\n"
"color:rgb(102, 220, 220);\n"
"border-radius:none;")
        self.textBrowser_Time.setObjectName("textBrowser_Time")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 150, 650, 500))
        self.frame_3.setStyleSheet("background-color:rgb(102,220,220);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.textBrowser_Terminal = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser_Terminal.setGeometry(QtCore.QRect(0, 0, 650, 500))
        self.textBrowser_Terminal.setStyleSheet("border: 2px solid rgb(102, 220, 220);\n"
"font-size:20px;\n"
"color:rgb(246, 245, 244);")
        self.textBrowser_Terminal.setObjectName("textBrowser_Terminal")
        ALAN.setCentralWidget(self.centralwidget)

        self.retranslateUi(ALAN)
        QtCore.QMetaObject.connectSlotsByName(ALAN)

    def retranslateUi(self, ALAN):
        _translate = QtCore.QCoreApplication.translate
        ALAN.setWindowTitle(_translate("ALAN", "ALAN"))
        self.Exit_Button.setText(_translate("ALAN", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ALAN = QtWidgets.QMainWindow()
    ui = Ui_ALAN()
    ui.setupUi(ALAN)
    ALAN.show()
    sys.exit(app.exec_())
